---
title: Energy, Environment, Electricity, and Economics
subtitle: A primer on energy and climate policy in California
author:
  - Alex Campbell
keywords:
  - energy
  - economics
  - California
  - policy
  - climate change
---
